# Generated by Django 4.2.6 on 2023-10-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPenangkapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alat_tangkap', models.CharField(choices=[('Lempura Dasar', 'Lempura Dasar'), ('Payang', 'Payang'), ('Bagan Berperahu', 'Bagan Berperahu'), ('Jaring Insang Tetap', 'Jaring Insang Tetap'), ('Jaring Insang Berlapis', 'Jaring Insang Berlapis')], default='Lempura Dasar', max_length=255)),
                ('hasil_tangkapan', models.TextField()),
            ],
        ),
    ]
