# Generated by Django 4.2.6 on 2023-10-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishtograph', '0002_remove_datapenangkapan_hasil_tangkapan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapenangkapan',
            name='hasil_tangkapan',
            field=models.TextField(default=''),
        ),
    ]
