# Generated by Django 4.2.6 on 2023-10-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishtograph', '0003_datapenangkapan_hasil_tangkapan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kapal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kapal', models.CharField(max_length=100)),
                ('besar_gt', models.IntegerField()),
                ('alat_tangkap_kapal', models.CharField(choices=[('LD', 'Lempura Dasar'), ('PG', 'Payang'), ('BB', 'Bagan Berperahu'), ('JIP', 'Jaring Insang Tetap'), ('JIB', 'Jaring Insang Berlapis')], default='LD', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nelayan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_nelayan', models.CharField(max_length=200)),
                ('umur', models.IntegerField()),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='datapenangkapan',
            name='hasil_tangkapan',
        ),
        migrations.AddField(
            model_name='datapenangkapan',
            name='tanggal_penangkapan',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='HasilTangkapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ikan', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('data_penangkapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishtograph.datapenangkapan')),
            ],
        ),
    ]
