# Generated by Django 4.2.6 on 2023-10-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishtograph', '0004_kapal_nelayan_remove_datapenangkapan_hasil_tangkapan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasiltangkapan',
            name='data_penangkapan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_tangkapan', to='fishtograph.datapenangkapan'),
        ),
    ]
