# Generated by Django 4.2.6 on 2023-10-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishtograph', '0005_alter_hasiltangkapan_data_penangkapan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapenangkapan',
            name='alat_tangkap',
            field=models.CharField(choices=[('Lempura Dasar', 'Lempura Dasar'), ('Payang', 'Payang'), ('Bagan Berperahu', 'Bagan Berperahu'), ('Jaring Insang Tetap', 'Jaring Insang Tetap'), ('Jaring Insang Berlapis', 'Jaring Insang Berlapis')], default='Lempura Dasar', max_length=255),
        ),
        migrations.AlterField(
            model_name='kapal',
            name='alat_tangkap_kapal',
            field=models.CharField(choices=[('Lempura Dasar', 'Lempura Dasar'), ('Payang', 'Payang'), ('Bagan Berperahu', 'Bagan Berperahu'), ('Jaring Insang Tetap', 'Jaring Insang Tetap'), ('Jaring Insang Berlapis', 'Jaring Insang Berlapis')], default='Lempura Dasar', max_length=255),
        ),
    ]
