# Generated by Django 4.2.6 on 2023-10-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishtograph', '0006_alter_datapenangkapan_alat_tangkap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HargaIkan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ikan', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='datapenangkapan',
            name='alat_tangkap',
            field=models.CharField(choices=[('Lempura Dasar', 'Lempura Dasar'), ('Payang', 'Payang'), ('Bagan Berperahu', 'Bagan Berperahu'), ('Jaring Insang Tetap', 'Jaring Insang Tetap'), ('Jaring Insang Berlapis', 'Jaring Insang Berlapis'), ('Bubu (Pots)', 'Bubu (Pots)'), ('Bubu Bersayap (Fyke Nets)', 'Bubu Bersayap (Fyke Nets)')], default='Lempura Dasar', max_length=255),
        ),
        migrations.AlterField(
            model_name='kapal',
            name='alat_tangkap_kapal',
            field=models.CharField(choices=[('Lempura Dasar', 'Lempura Dasar'), ('Payang', 'Payang'), ('Bagan Berperahu', 'Bagan Berperahu'), ('Jaring Insang Tetap', 'Jaring Insang Tetap'), ('Jaring Insang Berlapis', 'Jaring Insang Berlapis'), ('Bubu (Pots)', 'Bubu (Pots)'), ('Bubu Bersayap (Fyke Nets)', 'Bubu Bersayap (Fyke Nets)')], default='Lempura Dasar', max_length=255),
        ),
    ]
